Repository gasp-xyz/mangata-node, pull requests merged in 2021-08, with the labels that each got.

#108 select e2e branch from param
  .github/workflows/docker-image.yml
Labels: enhancement, skip-e2e-tests, skip-publish

#112 Added SemVer scripts
  .gitignore
  .versionrc
  CHANGELOG.md
  node/Cargo.toml
  package.json
  versionUpdater.js
  yarn.lock
Labels: enhancement

#118 Feature/when run e2e use branch by default
  .github/workflows/docker-image.yml
Labels: skip-build, skip-publish
