Repository gasp-xyz/mangata-node, pull requests merged in 2022-07, with the labels that each got.

#291 Update release.yml
  .github/workflows/release.yml
Labels: skip-e2e-tests, skip-build, skip-publish

#287 Feature/channels env
  Cargo.lock
  devops/dockerfiles/node/Dockerfile
  launch/.editorconfig
  launch/.gitignore
  launch/README.md
  launch/config.yml
  launch/karura-mangata.yml
  launch/package-lock.json
  launch/package.json
  launch/yarn.lock
  node/Cargo.toml
Labels: skip-e2e-tests

#294 fix docker deployment to update 'latest' tag on merge to develop
  .github/workflows/ci.yml
  devops/parachain/config/state
  devops/parachain/config/wasm
Labels: skip-e2e-tests

#290 bump orml to reference - Replaced xtokens transfer weight hooks with …
  Cargo.lock
  Cargo.toml
  runtime/mangata-kusama/src/lib.rs
  runtime/mangata-rococo/src/lib.rs
Labels: skip-e2e-tests

#286 Split e2e tests into multiple parallel jobs
  .github/workflows/ci.yml
Labels: skip-build, skip-publish
